-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_protocol]: function definitions
import Aeneas
import Libsignal.Code.Types
import Libsignal.Code.FunsPre
import Libsignal.Code.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libsignal_protocol


/-- Trait implementation: [core::ops::deref::{core::ops::deref::Deref<T> for &0 mut (T)}]
    Source: '/rustc/library/core/src/ops/deref.rs', lines 169:0-169:38
    Name pattern: [core::ops::deref::Deref<&'0 mut @T, @T>] -/
@[reducible, rust_trait_impl "core::ops::deref::Deref<&'0 mut @T, @T>"]
def Mut0T.Insts.CoreOpsDerefDeref (T : Type) : core.ops.deref.Deref T T := {
  deref := Mut0T.Insts.CoreOpsDerefDeref.deref
}

/-- Trait implementation: [core::ops::deref::{core::ops::deref::DerefMut<T> for &0 mut (T)}]
    Source: '/rustc/library/core/src/ops/deref.rs', lines 279:0-279:41
    Name pattern: [core::ops::deref::DerefMut<&'0 mut @T, @T>] -/
@[reducible, rust_trait_impl "core::ops::deref::DerefMut<&'0 mut @T, @T>"]
def Mut0T.Insts.CoreOpsDerefDerefMut (T : Type) : core.ops.deref.DerefMut T T
  := {
  derefInst := Mut0T.Insts.CoreOpsDerefDeref T
  deref_mut := Mut0T.Insts.CoreOpsDerefDerefMut.deref_mut
}

/-- [libsignal_core::address::{core::cmp::PartialEq<libsignal_core::address::ServiceIdKind> for libsignal_core::address::ServiceIdKind}::eq]:
    Source: 'rust/core/src/address.rs', lines 16:28-16:37
    Name pattern: [libsignal_core::address::{core::cmp::PartialEq<libsignal_core::address::ServiceIdKind, libsignal_core::address::ServiceIdKind>}::eq]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::cmp::PartialEq<libsignal_core::address::ServiceIdKind, libsignal_core::address::ServiceIdKind>}::eq"]
def libsignal_core.address.ServiceIdKind.Insts.CoreCmpPartialEqServiceIdKind.eq
  (self : libsignal_core.address.ServiceIdKind)
  (other : libsignal_core.address.ServiceIdKind) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [libsignal_core::address::{core::convert::TryFrom<u8, derive_more::convert::try_from::TryFromReprError<u8>> for libsignal_core::address::ServiceIdKind}::try_from]:
    Source: 'rust/core/src/address.rs', lines 16:43-16:63
    Name pattern: [libsignal_core::address::{core::convert::TryFrom<libsignal_core::address::ServiceIdKind, u8, derive_more::convert::try_from::TryFromReprError<u8>>}::try_from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::TryFrom<libsignal_core::address::ServiceIdKind, u8, derive_more::convert::try_from::TryFromReprError<u8>>}::try_from"]
def
  libsignal_core.address.ServiceIdKind.Insts.CoreConvertTryFromU8TryFromReprErrorU8.try_from
  (val : Std.U8) :
  Result (core.result.Result libsignal_core.address.ServiceIdKind
    (derive_more.convert.try_from.TryFromReprError Std.U8))
  := do
  match val with
  | 0#uscalar =>
    ok (core.result.Result.Ok libsignal_core.address.ServiceIdKind.Aci)
  | 1#uscalar =>
    ok (core.result.Result.Ok libsignal_core.address.ServiceIdKind.Pni)
  | _ =>
    let tfre ← derive_more.convert.try_from.TryFromReprError.new val
    ok (core.result.Result.Err tfre)

/-- [libsignal_core::address::{core::convert::From<libsignal_core::address::ServiceIdKind> for u8}::from]:
    Source: 'rust/core/src/address.rs', lines 27:4-27:41
    Name pattern: [libsignal_core::address::{core::convert::From<u8, libsignal_core::address::ServiceIdKind>}::from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::From<u8, libsignal_core::address::ServiceIdKind>}::from"]
def U8.Insts.CoreConvertFromServiceIdKind.from
  (value : libsignal_core.address.ServiceIdKind) : Result Std.U8 := do
  let value1 := read_discriminant value
  ok (UScalar.cast .U8 value1)

/-- Trait implementation: [libsignal_core::address::{core::convert::From<libsignal_core::address::ServiceIdKind> for u8}]
    Source: 'rust/core/src/address.rs', lines 26:0-26:31
    Name pattern: [core::convert::From<u8, libsignal_core::address::ServiceIdKind>] -/
@[reducible, rust_trait_impl
  "core::convert::From<u8, libsignal_core::address::ServiceIdKind>"]
def U8.Insts.CoreConvertFromServiceIdKind : core.convert.From Std.U8
  libsignal_core.address.ServiceIdKind := {
  from_ := U8.Insts.CoreConvertFromServiceIdKind.from
}

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::from_uuid]:
    Source: 'rust/core/src/address.rs', lines 77:4-77:42
    Name pattern: [libsignal_core::address::{libsignal_core::address::SpecificServiceId<@KIND>}::from_uuid] -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::SpecificServiceId<@KIND>}::from_uuid"]
def libsignal_core.address.SpecificServiceId.from_uuid
  (KIND : Std.U8) (uuid : uuid.Uuid) :
  Result (libsignal_core.address.SpecificServiceId KIND)
  := do
  ok { uuid }

/-- [libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<KIND>> for uuid::Uuid}::from]:
    Source: 'rust/core/src/address.rs', lines 151:4-151:51
    Name pattern: [libsignal_core::address::{core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>}::from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>}::from"]
def uuid.Uuid.Insts.CoreConvertFromSpecificServiceId.from
  {KIND : Std.U8} (value : libsignal_core.address.SpecificServiceId KIND) :
  Result uuid.Uuid
  := do
  ok value.uuid

/-- Trait implementation: [libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<KIND>> for uuid::Uuid}]
    Source: 'rust/core/src/address.rs', lines 149:0-149:59
    Name pattern: [core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>] -/
@[reducible, rust_trait_impl
  "core::convert::From<uuid::Uuid, libsignal_core::address::SpecificServiceId<@KIND>>"]
def uuid.Uuid.Insts.CoreConvertFromSpecificServiceId (KIND : Std.U8) :
  core.convert.From uuid.Uuid (libsignal_core.address.SpecificServiceId KIND)
  := {
  from_ := uuid.Uuid.Insts.CoreConvertFromSpecificServiceId.from
}

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::raw_uuid]:
    Source: 'rust/core/src/address.rs', lines 288:4-288:33
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::raw_uuid]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::raw_uuid"]
def libsignal_core.address.ServiceId.raw_uuid
  (self : libsignal_core.address.ServiceId) : Result uuid.Uuid := do
  match self with
  | libsignal_core.address.ServiceId.Aci aci =>
    core.convert.IntoFrom.into
      (uuid.Uuid.Insts.CoreConvertFromSpecificServiceId 0#u8) aci
  | libsignal_core.address.ServiceId.Pni pni =>
    core.convert.IntoFrom.into
      (uuid.Uuid.Insts.CoreConvertFromSpecificServiceId 1#u8) pni

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::kind]:
    Source: 'rust/core/src/address.rs', lines 195:4-195:39
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::kind]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::kind"]
def libsignal_core.address.ServiceId.kind
  (self : libsignal_core.address.ServiceId) :
  Result libsignal_core.address.ServiceIdKind
  := do
  match self with
  | libsignal_core.address.ServiceId.Aci _ =>
    ok libsignal_core.address.ServiceIdKind.Aci
  | libsignal_core.address.ServiceId.Pni _ =>
    ok libsignal_core.address.ServiceIdKind.Pni

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 216:4-216:81
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_fixed_width_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_fixed_width_binary"]
def libsignal_core.address.ServiceId.service_id_fixed_width_binary
  (self : libsignal_core.address.ServiceId) :
  Result (Array Std.U8 17#usize)
  := do
  let result := Array.repeat 17#usize 0#u8
  let sik ← libsignal_core.address.ServiceId.kind self
  let i ←
    core.convert.IntoFrom.into U8.Insts.CoreConvertFromServiceIdKind sik
  let result1 ← Array.update result 0#usize i
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) result1
      { start := 1#usize }
  let u ← libsignal_core.address.ServiceId.raw_uuid self
  let a ← uuid.Uuid.as_bytes u
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 206:4-206:46
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_binary"]
def libsignal_core.address.ServiceId.service_id_binary
  (self : libsignal_core.address.ServiceId) :
  Result (alloc.vec.Vec Std.U8)
  := do
  match self with
  | libsignal_core.address.ServiceId.Aci aci =>
    let a ← uuid.Uuid.as_bytes aci.uuid
    let s ← lift (Array.to_slice a)
    alloc.slice.Slice.to_vec core.clone.CloneU8 s
  | libsignal_core.address.ServiceId.Pni _ =>
    let a ←
      libsignal_core.address.ServiceId.service_id_fixed_width_binary self
    let s ← lift (Array.to_slice a)
    alloc.slice.Slice.to_vec core.clone.CloneU8 s

/-- [libsignal_core::address::{core::convert::From<uuid::Uuid> for libsignal_core::address::SpecificServiceId<KIND>}::from]:
    Source: 'rust/core/src/address.rs', lines 144:4-144:32
    Name pattern: [libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>}::from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>}::from"]
def libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid.from
  (KIND : Std.U8) (value : uuid.Uuid) :
  Result (libsignal_core.address.SpecificServiceId KIND)
  := do
  libsignal_core.address.SpecificServiceId.from_uuid KIND value

/-- Trait implementation: [libsignal_core::address::{core::convert::From<uuid::Uuid> for libsignal_core::address::SpecificServiceId<KIND>}]
    Source: 'rust/core/src/address.rs', lines 142:0-142:59
    Name pattern: [core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>] -/
@[reducible, rust_trait_impl
  "core::convert::From<libsignal_core::address::SpecificServiceId<@KIND>, uuid::Uuid>"]
def libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid (KIND :
  Std.U8) : core.convert.From (libsignal_core.address.SpecificServiceId KIND)
  uuid.Uuid := {
  from_ :=
    libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid.from
    KIND
}

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 254:4-256:21
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_fixed_width_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_fixed_width_binary"]
def libsignal_core.address.ServiceId.parse_from_service_id_fixed_width_binary
  (bytes : Array Std.U8 17#usize) :
  Result (Option libsignal_core.address.ServiceId)
  := do
  let s ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) bytes
      { start := 1#usize }
  let r ← uuid.builder.Uuid.from_slice s
  let o ← core.result.Result.ok r
  let cf ←
    core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← Array.index_usize bytes 0#usize
    let r1 ←
      libsignal_core.address.ServiceIdKind.Insts.CoreConvertTryFromU8TryFromReprErrorU8.try_from
        i
    let o1 ← core.result.Result.ok r1
    let cf1 ←
      core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      match val1 with
      | libsignal_core.address.ServiceIdKind.Aci =>
        let ssi ←
          core.convert.IntoFrom.into
            (libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid
            0#u8) val
        ok (some (libsignal_core.address.ServiceId.Aci ssi))
      | libsignal_core.address.ServiceIdKind.Pni =>
        let ssi ←
          core.convert.IntoFrom.into
            (libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid
            1#u8) val
        ok (some (libsignal_core.address.ServiceId.Pni ssi))
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        libsignal_core.address.ServiceId residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      libsignal_core.address.ServiceId residual

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 234:4-234:69
    Name pattern: [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_binary]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_binary"]
def libsignal_core.address.ServiceId.parse_from_service_id_binary
  (bytes : Slice Std.U8) :
  Result (Option libsignal_core.address.ServiceId)
  := do
  let i := Slice.len bytes
  match i.val with
  | 16 =>
    let r ← uuid.builder.Uuid.from_slice bytes
    let o ← core.result.Result.ok r
    let cf ←
      core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let ssi ←
        core.convert.IntoFrom.into
          (libsignal_core.address.SpecificServiceId.Insts.CoreConvertFromUuid
          0#u8) val
      ok (some (libsignal_core.address.ServiceId.Aci ssi))
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        libsignal_core.address.ServiceId residual
  | 17 =>
    let r ← core.array.TryFromSharedArraySlice.try_from 17#usize bytes
    let a ←
      core.result.Result.expect core.fmt.DebugTryFromSliceError r (toStr
        "already measured")
    let o ←
      libsignal_core.address.ServiceId.parse_from_service_id_fixed_width_binary
        a
    let cf ←
      core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let sik ← libsignal_core.address.ServiceId.kind val
      let b ←
        libsignal_core.address.ServiceIdKind.Insts.CoreCmpPartialEqServiceIdKind.eq
          sik libsignal_core.address.ServiceIdKind.Aci
      if b
      then ok none
      else ok (some val)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        libsignal_core.address.ServiceId residual
  | _ => ok none

/-- [libsignal_core::address::MAX_VALID_DEVICE_ID]
    Source: 'rust/core/src/address.rs', lines 719:0-719:29
    Name pattern: [libsignal_core::address::MAX_VALID_DEVICE_ID] -/
@[global_simps, irreducible, rust_const
  "libsignal_core::address::MAX_VALID_DEVICE_ID"]
def libsignal_core.address.MAX_VALID_DEVICE_ID : Std.U8 := 127#u8

/-- [libsignal_core::address::{libsignal_core::address::DeviceId}::new_nonzero]:
    Source: 'rust/core/src/address.rs', lines 710:4-710:76
    Name pattern: [libsignal_core::address::{libsignal_core::address::DeviceId}::new_nonzero]
    Visibility: public -/
@[rust_fun
  "libsignal_core::address::{libsignal_core::address::DeviceId}::new_nonzero"]
def libsignal_core.address.DeviceId.new_nonzero
  (id : core.num.nonzero.NonZero Std.U8 core.num.niche_types.NonZeroU8Inner) :
  Result (core.result.Result libsignal_core.address.DeviceId
    libsignal_core.address.InvalidDeviceId)
  := do
  let i ←
    core.num.nonzero.NonZero.get
      U8.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner id
  if i <= libsignal_core.address.MAX_VALID_DEVICE_ID
  then ok (core.result.Result.Ok { id })
  else ok (core.result.Result.Err ())

/-- [libsignal_core::curve::{libsignal_core::curve::KeyType}::value]:
    Source: 'rust/core/src/curve.rs', lines 26:4-26:25
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::KeyType}::value] -/
@[rust_fun "libsignal_core::curve::{libsignal_core::curve::KeyType}::value"]
def libsignal_core.curve.KeyType.value
  (self : libsignal_core.curve.KeyType) : Result Std.U8 := do
  ok 5#u8

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::key_type]:
    Source: 'rust/core/src/curve.rs', lines 159:4-159:37
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::PublicKey}::key_type]
    Visibility: public -/
@[rust_fun
  "libsignal_core::curve::{libsignal_core::curve::PublicKey}::key_type"]
def libsignal_core.curve.PublicKey.key_type
  (self : libsignal_core.curve.PublicKey) :
  Result libsignal_core.curve.KeyType
  := do
  ok libsignal_core.curve.KeyType.Djb

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::scalar_is_in_range]:
    Source: 'rust/core/src/curve.rs', lines 176:4-176:40
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::PublicKey}::scalar_is_in_range] -/
@[rust_fun
  "libsignal_core::curve::{libsignal_core::curve::PublicKey}::scalar_is_in_range"]
def libsignal_core.curve.PublicKey.scalar_is_in_range
  (self : libsignal_core.curve.PublicKey) : Result Bool := do
  let ⟨ k ⟩ := self.key
  let i ← Array.index_usize k 31#usize
  let i1 ← lift (i &&& 128#u8)
  let b ←
    if i1 != 0#u8
    then ok true
    else
      do
      let i2 ← Array.index_usize k 0#usize
      let i3 ← lift (core.num.U8.wrapping_sub 0#u8 19#u8)
      if i2 >= i3
      then
        let s ←
          core.array.Array.index (core.ops.index.IndexSlice
            (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) k
            { start := 1#usize, «end» := 31#usize }
        let a := Array.repeat 30#usize 255#u8
        let b1 ←
          Slice.Insts.CoreCmpPartialEqArray.eq core.cmp.PartialEqU8 s a
        if b1
        then ok (i == 127#u8)
        else ok false
      else ok false
  ok (¬ b)

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<(core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164> for libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure}::call_once]:
    Source: 'rust/core/src/e164.rs', lines 27:55-27:62
    Name pattern: [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>}::call_once] -/
@[rust_fun
  "libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>}::call_once"]
def
  libsignal_core.e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164.call_once
  (c : libsignal_core.e164.E164.from_be_bytes.closure)
  (tupled_args : core.num.nonzero.NonZero Std.U64
  core.num.niche_types.NonZeroU64Inner) :
  Result libsignal_core.e164.E164
  := do
  ok { inner := tupled_args }

/-- Trait implementation: [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{core::ops::function::FnOnce<(core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164> for libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure}]
    Source: 'rust/core/src/e164.rs', lines 27:55-27:62
    Name pattern: [core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnOnce<libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure, (core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>), libsignal_core::e164::E164>"]
def
  libsignal_core.e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164
  : core.ops.function.FnOnce libsignal_core.e164.E164.from_be_bytes.closure
  (core.num.nonzero.NonZero Std.U64 core.num.niche_types.NonZeroU64Inner)
  libsignal_core.e164.E164 := {
  call_once :=
    libsignal_core.e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164.call_once
}

/-- [libsignal_core::version::VERSION]
    Source: 'rust/core/src/version.rs', lines 8:0-8:23
    Name pattern: [libsignal_core::version::VERSION]
    Visibility: public -/
@[global_simps, irreducible, rust_const "libsignal_core::version::VERSION"]
def libsignal_core.version.VERSION : Str := toStr "0.94.0"

/-- Trait implementation: [rand_core::{rand_core::RngCore for T}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 158:0-160:23
    Name pattern: [rand_core::RngCore<@T>] -/
@[reducible, rust_trait_impl "rand_core::RngCore<@T>"]
def rand_core.RngCore.Blanket {T : Type} {Clause0_Clause0_Target : Type}
  (coreopsderefDerefMutInst : core.ops.deref.DerefMut T Clause0_Clause0_Target)
  (RngCoreInst : rand_core.RngCore Clause0_Clause0_Target) : rand_core.RngCore
  T := {
  next_u32 := rand_core.RngCore.Blanket.next_u32 coreopsderefDerefMutInst
    RngCoreInst
  next_u64 := rand_core.RngCore.Blanket.next_u64 coreopsderefDerefMutInst
    RngCoreInst
  fill_bytes := rand_core.RngCore.Blanket.fill_bytes coreopsderefDerefMutInst
    RngCoreInst
}

/-- Trait implementation: [rand_core::{rand_core::CryptoRng for T}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 206:0-206:60
    Name pattern: [rand_core::CryptoRng<@T>] -/
@[reducible, rust_trait_impl "rand_core::CryptoRng<@T>"]
def rand_core.CryptoRng.Blanket {T : Type} {Clause0_Clause0_Target : Type}
  (coreopsderefDerefMutInst : core.ops.deref.DerefMut T Clause0_Clause0_Target)
  (CryptoRngInst : rand_core.CryptoRng Clause0_Clause0_Target) :
  rand_core.CryptoRng T := {
  RngCoreInst := rand_core.RngCore.Blanket coreopsderefDerefMutInst
    CryptoRngInst.RngCoreInst
}

/-- [libsignal_protocol::error::{core::convert::From<libsignal_core::curve::CurveError> for libsignal_protocol::error::SignalProtocolError}::from]:
    Source: 'rust/protocol/src/error.rs', lines 126:4-133:5
    Visibility: public -/
def error.SignalProtocolError.Insts.CoreConvertFromCurveError.from
  (e : libsignal_core.curve.CurveError) :
  Result error.SignalProtocolError
  := do
  match e with
  | libsignal_core.curve.CurveError.NoKeyTypeIdentifier =>
    ok error.SignalProtocolError.NoKeyTypeIdentifier
  | libsignal_core.curve.CurveError.BadKeyType raw1 =>
    ok (error.SignalProtocolError.BadKeyType raw1)
  | libsignal_core.curve.CurveError.BadKeyLength key_type len =>
    ok (error.SignalProtocolError.BadKeyLength key_type len)
  | libsignal_core.curve.CurveError.InvalidKeyAgreement =>
    ok error.SignalProtocolError.InvalidKeyAgreement

/-- Trait implementation: [libsignal_protocol::error::{core::convert::From<libsignal_core::curve::CurveError> for libsignal_protocol::error::SignalProtocolError}]
    Source: 'rust/protocol/src/error.rs', lines 125:0-134:1 -/
@[reducible]
def error.SignalProtocolError.Insts.CoreConvertFromCurveError :
  core.convert.From error.SignalProtocolError libsignal_core.curve.CurveError
  := {
  from_ := error.SignalProtocolError.Insts.CoreConvertFromCurveError.from
}

/-- [libsignal_protocol::identity_key::{libsignal_protocol::identity_key::IdentityKey}::public_key]:
    Source: 'rust/protocol/src/identity_key.rs', lines 36:4-38:5
    Visibility: public -/
def identity_key.IdentityKey.impl.public_key
  (self : identity_key.IdentityKey) :
  Result libsignal_core.curve.PublicKey
  := do
  ok self.public_key

/-- [libsignal_protocol::identity_key::{libsignal_protocol::identity_key::IdentityKeyPair}::private_key]:
    Source: 'rust/protocol/src/identity_key.rs', lines 149:4-151:5
    Visibility: public -/
def identity_key.IdentityKeyPair.impl.private_key
  (self : identity_key.IdentityKeyPair) :
  Result libsignal_core.curve.PrivateKey
  := do
  ok self.private_key

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::KeyType}::value]:
    Source: 'rust/protocol/src/kem.rs', lines 219:4-227:5 -/
def kem.KeyType.value (self : kem.KeyType) : Result Std.U8 := do
  ok 8#u8

/-- Trait implementation: [libsignal_protocol::kem::{libsignal_protocol::kem::KeyKind for libsignal_protocol::kem::Public}]
    Source: 'rust/protocol/src/kem.rs', lines 264:0-268:1 -/
@[reducible]
def kem.Public.Insts.Libsignal_protocolKemKeyKind : kem.KeyKind kem.Public := {
  key_length := kem.Public.Insts.Libsignal_protocolKemKeyKind.key_length
}

/-- [libsignal_protocol::kem::{core::ops::deref::Deref<[u8]> for libsignal_protocol::kem::KeyMaterial<T>}::deref]:
    Source: 'rust/protocol/src/kem.rs', lines 278:9-278:27
    Visibility: public -/
def kem.KeyMaterial.Insts.CoreOpsDerefDerefSliceU8.deref
  {T : Type} {Clause1_Target : Type} (KeyKindInst : kem.KeyKind T)
  (coreopsderefDerefBoxSliceU8Clause1_TargetInst : core.ops.deref.Deref (Slice
  Std.U8) Clause1_Target) (self : kem.KeyMaterial T) :
  Result (Slice Std.U8)
  := do
  ok (alloc.boxed.Box.deref self.data)

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::Ciphertext}::serialize]:
    Source: 'rust/protocol/src/kem.rs', lines 540:4-545:5
    Visibility: public -/
def kem.Ciphertext.serialize
  (self : kem.Ciphertext) : Result (Slice Std.U8) := do
  let i := Slice.len self.data
  let i1 ← 1#usize + i
  let result := alloc.vec.Vec.with_capacity Std.U8 i1
  let i2 ← kem.KeyType.value self.key_type
  let result1 ← alloc.vec.Vec.push result i2
  let result2 ←
    alloc.vec.Vec.extend_from_slice core.clone.CloneU8 result1 self.data
  alloc.vec.Vec.into_boxed_slice Global result2

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Public>}::encapsulate::{core::ops::function::FnOnce<(libsignal_protocol::kem::BadKEMKeyLength), libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Public>}::encapsulate::closure<0, R>}::call_once]:
    Source: 'rust/protocol/src/kem.rs', lines 368:21-370:13 -/
def
  kem.KeyPublic.encapsulate.closure.Insts.CoreOpsFunctionFnOnceTupleBadKEMKeyLengthSignalProtocolError.call_once
  {R : Type} (rand_coreCryptoRngInst : rand_core.CryptoRng R)
  (c : kem.KeyPublic.encapsulate.closure R) (tupled_args : kem.BadKEMKeyLength)
  :
  Result error.SignalProtocolError
  := do
  let s ←
    kem.KeyMaterial.Insts.CoreOpsDerefDerefSliceU8.deref
      kem.Public.Insts.Libsignal_protocolKemKeyKind
      (core.ops.deref.DerefBoxInst (Slice Std.U8)) c.key_data
  let i := Slice.len s
  ok (error.SignalProtocolError.BadKEMKeyLength c.key_type i)

/-- Trait implementation: [libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Public>}::encapsulate::{core::ops::function::FnOnce<(libsignal_protocol::kem::BadKEMKeyLength), libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Public>}::encapsulate::closure<0, R>}]
    Source: 'rust/protocol/src/kem.rs', lines 368:21-370:13 -/
@[reducible]
def
  kem.KeyPublic.encapsulate.closure.Insts.CoreOpsFunctionFnOnceTupleBadKEMKeyLengthSignalProtocolError
  {R : Type} (rand_coreCryptoRngInst : rand_core.CryptoRng R) :
  core.ops.function.FnOnce (kem.KeyPublic.encapsulate.closure R)
  kem.BadKEMKeyLength error.SignalProtocolError := {
  call_once :=
    kem.KeyPublic.encapsulate.closure.Insts.CoreOpsFunctionFnOnceTupleBadKEMKeyLengthSignalProtocolError.call_once
    rand_coreCryptoRngInst
}

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Public>}::encapsulate]:
    Source: 'rust/protocol/src/kem.rs', lines 356:4-380:5
    Visibility: public -/
def kem.KeyPublic.encapsulate
  {R : Type} (rand_coreCryptoRngInst : rand_core.CryptoRng R)
  (self : kem.Key kem.Public) (csprng : R) :
  Result ((core.result.Result ((Slice Std.U8) × (Slice Std.U8))
    error.SignalProtocolError) × R)
  := do
  let (r, csprng1) ←
    kem.kyber1024.Parameters.Insts.Libsignal_protocolKemParameters.encapsulate
      rand_coreCryptoRngInst self.key_data csprng
  let r1 ←
    core.result.Result.map_err
      (kem.KeyPublic.encapsulate.closure.Insts.CoreOpsFunctionFnOnceTupleBadKEMKeyLengthSignalProtocolError
      rand_coreCryptoRngInst) r self
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (ss, ct) := val
    let s ←
      kem.Ciphertext.serialize { key_type := self.key_type, data := ct }
    ok (core.result.Result.Ok (ss, s), csprng1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r2 ←
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        ((Slice Std.U8) × (Slice Std.U8)) (core.convert.FromSame
        error.SignalProtocolError) residual
    ok (r2, csprng1)

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::new]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 129:4-148:5
    Visibility: public -/
def pqxdh.InitiatorParameters.new
  (our_identity_key_pair : identity_key.IdentityKeyPair)
  (our_ephemeral_key_pair : libsignal_core.curve.KeyPair)
  (their_identity_key : identity_key.IdentityKey)
  (their_signed_pre_key : libsignal_core.curve.PublicKey)
  (their_ratchet_key : libsignal_core.curve.PublicKey)
  (their_kyber_pre_key : kem.Key kem.Public) (self_session : Bool) :
  Result pqxdh.InitiatorParameters
  := do
  ok
    {
      our_identity_key_pair,
      our_ephemeral_key_pair,
      their_identity_key,
      their_signed_pre_key,
      their_one_time_pre_key := none,
      their_ratchet_key,
      their_kyber_pre_key,
      self_session
    }

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::set_their_one_time_pre_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 150:4-152:5
    Visibility: public -/
def pqxdh.InitiatorParameters.set_their_one_time_pre_key
  (self : pqxdh.InitiatorParameters)
  (ec_public : libsignal_core.curve.PublicKey) :
  Result pqxdh.InitiatorParameters
  := do
  ok { self with their_one_time_pre_key := (some ec_public) }

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::our_identity_key_pair]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 155:4-157:5
    Visibility: public -/
def pqxdh.InitiatorParameters.impl.our_identity_key_pair
  (self : pqxdh.InitiatorParameters) :
  Result identity_key.IdentityKeyPair
  := do
  ok self.our_identity_key_pair

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::our_ephemeral_key_pair]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 160:4-162:5
    Visibility: public -/
def pqxdh.InitiatorParameters.impl.our_ephemeral_key_pair
  (self : pqxdh.InitiatorParameters) :
  Result libsignal_core.curve.KeyPair
  := do
  ok self.our_ephemeral_key_pair

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::their_identity_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 165:4-167:5
    Visibility: public -/
def pqxdh.InitiatorParameters.impl.their_identity_key
  (self : pqxdh.InitiatorParameters) : Result identity_key.IdentityKey := do
  ok self.their_identity_key

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::their_signed_pre_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 170:4-172:5
    Visibility: public -/
def pqxdh.InitiatorParameters.impl.their_signed_pre_key
  (self : pqxdh.InitiatorParameters) :
  Result libsignal_core.curve.PublicKey
  := do
  ok self.their_signed_pre_key

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::their_kyber_pre_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 180:4-182:5
    Visibility: public -/
def pqxdh.InitiatorParameters.impl.their_kyber_pre_key
  (self : pqxdh.InitiatorParameters) : Result (kem.Key kem.Public) := do
  ok self.their_kyber_pre_key

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::their_ratchet_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 185:4-187:5
    Visibility: public -/
def pqxdh.InitiatorParameters.impl.their_ratchet_key
  (self : pqxdh.InitiatorParameters) :
  Result libsignal_core.curve.PublicKey
  := do
  ok self.their_ratchet_key

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::self_session]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 190:4-192:5
    Visibility: public -/
def pqxdh.InitiatorParameters.impl.self_session
  (self : pqxdh.InitiatorParameters) : Result Bool := do
  ok self.self_session

/-- [libsignal_protocol::pqxdh::pqxdh_initiate]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 199:0-241:1 -/
def pqxdh.pqxdh_initiate
  {R : Type} (randrngRngInst : rand.rng.Rng R) (rand_coreCryptoRngInst :
  rand_core.CryptoRng R) (parameters1 : pqxdh.InitiatorParameters) (csprng : R)
  :
  Result ((core.result.Result pqxdh.InitiatorAgreement
    error.SignalProtocolError) × R)
  := do
  let i ← 32#usize * 6#usize
  let secrets := alloc.vec.Vec.with_capacity Std.U8 i
  let a := Array.repeat 32#usize 255#u8
  let s ← lift (Array.to_slice a)
  let secrets1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 secrets s
  let pk ←
    identity_key.IdentityKeyPair.impl.private_key
      parameters1.our_identity_key_pair
  let r ←
    libsignal_core.curve.PrivateKey.calculate_agreement pk
      parameters1.their_signed_pre_key
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let secrets2 ←
      alloc.vec.Vec.extend_from_slice core.clone.CloneU8 secrets1 val
    let pk1 ←
      identity_key.IdentityKey.impl.public_key parameters1.their_identity_key
    let r1 ←
      libsignal_core.curve.PrivateKey.calculate_agreement
        parameters1.our_ephemeral_key_pair.private_key pk1
    let cf1 ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let secrets3 ←
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 secrets2 val1
      let r2 ←
        libsignal_core.curve.PrivateKey.calculate_agreement
          parameters1.our_ephemeral_key_pair.private_key
          parameters1.their_signed_pre_key
      let cf2 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let secrets4 ←
          alloc.vec.Vec.extend_from_slice core.clone.CloneU8 secrets3 val2
        match parameters1.their_one_time_pre_key with
        | none =>
          let (r3, csprng1) ←
            kem.KeyPublic.encapsulate (rand_core.CryptoRng.Blanket
              (Mut0T.Insts.CoreOpsDerefDerefMut R) rand_coreCryptoRngInst)
              parameters1.their_kyber_pre_key csprng
          let cf3 ←
            core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
              r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue val3 =>
            let (ss, ct) := val3
            let s1 ← Box.Insts.CoreConvertAsRef.as_ref Global ss
            let secrets5 ←
              alloc.vec.Vec.extend_from_slice core.clone.CloneU8 secrets4 s1
            let s2 := alloc.vec.Vec.deref secrets5
            let hk ← pqxdh.HandshakeKeys.derive s2
            let csprng2 := csprng1
            ok (core.result.Result.Ok { keys := hk, kyber_ciphertext := ct },
              csprng2)
          | core.ops.control_flow.ControlFlow.Break residual =>
            let r4 ←
              core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                pqxdh.InitiatorAgreement (core.convert.FromSame
                error.SignalProtocolError) residual
            let csprng2 := csprng1
            ok (r4, csprng2)
        | some their_one_time_prekey =>
          let r3 ←
            libsignal_core.curve.PrivateKey.calculate_agreement
              parameters1.our_ephemeral_key_pair.private_key
              their_one_time_prekey
          let cf3 ←
            core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
              r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue val3 =>
            let secrets5 ←
              alloc.vec.Vec.extend_from_slice core.clone.CloneU8 secrets4 val3
            let (r4, csprng1) ←
              kem.KeyPublic.encapsulate (rand_core.CryptoRng.Blanket
                (Mut0T.Insts.CoreOpsDerefDerefMut R) rand_coreCryptoRngInst)
                parameters1.their_kyber_pre_key csprng
            let cf4 ←
              core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
                r4
            match cf4 with
            | core.ops.control_flow.ControlFlow.Continue val4 =>
              let (ss, ct) := val4
              let s1 ← Box.Insts.CoreConvertAsRef.as_ref Global ss
              let secrets6 ←
                alloc.vec.Vec.extend_from_slice core.clone.CloneU8 secrets5 s1
              let s2 := alloc.vec.Vec.deref secrets6
              let hk ← pqxdh.HandshakeKeys.derive s2
              let csprng2 := csprng1
              ok (core.result.Result.Ok { keys := hk, kyber_ciphertext := ct },
                csprng2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r5 ←
                core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                  pqxdh.InitiatorAgreement (core.convert.FromSame
                  error.SignalProtocolError) residual
              let csprng2 := csprng1
              ok (r5, csprng2)
          | core.ops.control_flow.ControlFlow.Break residual =>
            let r4 ←
              core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                pqxdh.InitiatorAgreement
                error.SignalProtocolError.Insts.CoreConvertFromCurveError
                residual
            ok (r4, csprng)
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r3 ←
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            pqxdh.InitiatorAgreement
            error.SignalProtocolError.Insts.CoreConvertFromCurveError residual
        ok (r3, csprng)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r2 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          pqxdh.InitiatorAgreement
          error.SignalProtocolError.Insts.CoreConvertFromCurveError residual
      ok (r2, csprng)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        pqxdh.InitiatorAgreement
        error.SignalProtocolError.Insts.CoreConvertFromCurveError residual
    ok (r1, csprng)

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::new]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 264:4-284:5
    Visibility: public -/
def pqxdh.RecipientParameters.new
  (our_identity_key_pair : identity_key.IdentityKeyPair)
  (our_signed_pre_key_pair : libsignal_core.curve.KeyPair)
  (our_one_time_pre_key_pair : Option libsignal_core.curve.KeyPair)
  (our_kyber_pre_key_pair : kem.KeyPair)
  (their_identity_key : identity_key.IdentityKey)
  (their_ephemeral_key : libsignal_core.curve.PublicKey)
  (their_kyber_ciphertext : Slice Std.U8) (self_session : Bool) :
  Result pqxdh.RecipientParameters
  := do
  ok
    {
      our_identity_key_pair,
      our_signed_pre_key_pair,
      our_one_time_pre_key_pair,
      our_kyber_pre_key_pair,
      their_identity_key,
      their_ephemeral_key,
      their_kyber_ciphertext,
      self_session
    }

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::our_identity_key_pair]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 287:4-289:5
    Visibility: public -/
def pqxdh.RecipientParameters.impl.our_identity_key_pair
  (self : pqxdh.RecipientParameters) :
  Result identity_key.IdentityKeyPair
  := do
  ok self.our_identity_key_pair

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::our_signed_pre_key_pair]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 292:4-294:5
    Visibility: public -/
def pqxdh.RecipientParameters.impl.our_signed_pre_key_pair
  (self : pqxdh.RecipientParameters) :
  Result libsignal_core.curve.KeyPair
  := do
  ok self.our_signed_pre_key_pair

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::our_kyber_pre_key_pair]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 302:4-304:5
    Visibility: public -/
def pqxdh.RecipientParameters.impl.our_kyber_pre_key_pair
  (self : pqxdh.RecipientParameters) : Result kem.KeyPair := do
  ok self.our_kyber_pre_key_pair

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::their_identity_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 307:4-309:5
    Visibility: public -/
def pqxdh.RecipientParameters.impl.their_identity_key
  (self : pqxdh.RecipientParameters) : Result identity_key.IdentityKey := do
  ok self.their_identity_key

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::their_ephemeral_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 312:4-314:5
    Visibility: public -/
def pqxdh.RecipientParameters.impl.their_ephemeral_key
  (self : pqxdh.RecipientParameters) :
  Result libsignal_core.curve.PublicKey
  := do
  ok self.their_ephemeral_key

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::their_kyber_ciphertext]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 317:4-319:5
    Visibility: public -/
def pqxdh.RecipientParameters.impl.their_kyber_ciphertext
  (self : pqxdh.RecipientParameters) : Result (Slice Std.U8) := do
  ok self.their_kyber_ciphertext

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::self_session]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 322:4-324:5
    Visibility: public -/
def pqxdh.RecipientParameters.impl.self_session
  (self : pqxdh.RecipientParameters) : Result Bool := do
  ok self.self_session


end libsignal_protocol

