-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_protocol]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Libsignal.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open libsignal_protocol


/-- [core::array::equality::{core::cmp::PartialEq<[U; N]> for [T]}::eq]:
    Source: '/rustc/library/core/src/array/equality.rs', lines 48:4-48:40
    Name pattern: [core::array::equality::{core::cmp::PartialEq<[@T], [@U; @N]>}::eq]
    Visibility: public -/
@[rust_fun "core::array::equality::{core::cmp::PartialEq<[@T], [@U; @N]>}::eq"]
axiom Slice.Insts.CoreCmpPartialEqArray.eq
  {T : Type} {U : Type} {N : Std.Usize} (cmpPartialEqInst : core.cmp.PartialEq
  T U) :
  Slice T → Array U N → Result Bool

/-- [core::num::nonzero::{core::num::nonzero::NonZero<T, Clause0_NonZeroInner>}::new]:
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 401:4-401:42
    Name pattern: [core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::new]
    Visibility: public -/
@[rust_fun
  "core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::new"]
axiom core.num.nonzero.NonZero.new
  {T : Type} {Clause0_NonZeroInner : Type} (ZeroablePrimitiveInst :
  core.num.nonzero.ZeroablePrimitive T Clause0_NonZeroInner) :
  T → Result (Option (core.num.nonzero.NonZero T Clause0_NonZeroInner))

/-- [core::num::nonzero::{core::num::nonzero::NonZero<T, Clause0_NonZeroInner>}::get]:
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 480:4-480:31
    Name pattern: [core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::get]
    Visibility: public -/
@[rust_fun
  "core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::get"]
axiom core.num.nonzero.NonZero.get
  {T : Type} {Clause0_NonZeroInner : Type} (ZeroablePrimitiveInst :
  core.num.nonzero.ZeroablePrimitive T Clause0_NonZeroInner) :
  core.num.nonzero.NonZero T Clause0_NonZeroInner → Result T

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1160:4-1162:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [core::option::{core::ops::try_trait::Try<T, core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2765:4-2765:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>, @T, core::option::Option<core::convert::Infallible>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>, @T, core::option::Option<core::convert::Infallible>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTryTOptionInfallible.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [core::result::{core::result::Result<T, E>}::ok]:
    Source: '/rustc/library/core/src/result.rs', lines 708:4-711:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::ok]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
axiom core.result.Result.ok
  {T : Type} {E : Type} : core.result.Result T E → Result (Option T)

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [alloc::string::{core::ops::deref::Deref<str> for alloc::string::String}::deref]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2824:4-2824:27
    Name pattern: [alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref"]
axiom alloc.string.String.Insts.CoreOpsDerefDerefStr.deref
  : String → Result Str

/-- [alloc::vec::{alloc::vec::Vec<T>}::into_boxed_slice]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1643:4-1643:52
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::into_boxed_slice]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::into_boxed_slice"]
axiom alloc.vec.Vec.into_boxed_slice
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (Slice T)

/-- [derive_more::convert::try_from::{derive_more::convert::try_from::TryFromReprError<T>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/derive_more-2.1.1/src/convert.rs', lines 29:8-29:42
    Name pattern: [derive_more::convert::try_from::{derive_more::convert::try_from::TryFromReprError<@T>}::new]
    Visibility: public -/
@[rust_fun
  "derive_more::convert::try_from::{derive_more::convert::try_from::TryFromReprError<@T>}::new"]
axiom derive_more.convert.try_from.TryFromReprError.new
  {T : Type} : T → Result (derive_more.convert.try_from.TryFromReprError T)

/-- [ghash::{core::clone::Clone for ghash::GHash}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ghash-0.5.1/src/lib.rs', lines 57:9-57:14
    Name pattern: [ghash::{core::clone::Clone<ghash::GHash>}::clone]
    Visibility: public -/
@[rust_fun "ghash::{core::clone::Clone<ghash::GHash>}::clone"]
axiom ghash.GHash.Insts.CoreCloneClone.clone
  : ghash.GHash → Result ghash.GHash

/-- [uuid::builder::{uuid::Uuid}::from_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/builder.rs', lines 364:4-364:49
    Name pattern: [uuid::builder::{uuid::Uuid}::from_bytes]
    Visibility: public -/
@[rust_fun "uuid::builder::{uuid::Uuid}::from_bytes"]
axiom uuid.builder.Uuid.from_bytes : Array Std.U8 16#usize → Result uuid.Uuid

/-- [uuid::{uuid::Uuid}::as_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/lib.rs', lines 790:4-790:42
    Name pattern: [uuid::{uuid::Uuid}::as_bytes]
    Visibility: public -/
@[rust_fun "uuid::{uuid::Uuid}::as_bytes"]
def uuid.Uuid.as_bytes (self : uuid.Uuid) : Result (Array Std.U8 16#usize) :=
  ok self.bytes

/-- A UUID byte-length error (returned when slice length ≠ 16). Hand-axiom for
the `.Err` branch of `from_slice`. -/
axiom uuid.error.Error.byteLengthError : uuid.error.Error

/-- [uuid::builder::{uuid::Uuid}::from_slice]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/builder.rs', lines 287:4-287:54
    Name pattern: [uuid::builder::{uuid::Uuid}::from_slice]
    Visibility: public -/
@[rust_fun "uuid::builder::{uuid::Uuid}::from_slice"]
noncomputable def uuid.builder.Uuid.from_slice
  (s : Slice Std.U8) : Result (core.result.Result uuid.Uuid uuid.error.Error) :=
  if h : s.len = 16#usize then
    ok (.Ok ⟨⟨s.val, by scalar_tac⟩⟩)
  else
    ok (.Err uuid.error.Error.byteLengthError)

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::verify_signature_for_multipart_message]:
    Source: 'rust/core/src/curve.rs', lines 138:4-142:13
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::PublicKey}::verify_signature_for_multipart_message]
    Visibility: public -/
@[rust_fun
  "libsignal_core::curve::{libsignal_core::curve::PublicKey}::verify_signature_for_multipart_message"]
axiom libsignal_core.curve.PublicKey.verify_signature_for_multipart_message
  :
  libsignal_core.curve.PublicKey → Slice (Slice Std.U8) → Slice Std.U8 →
    Result Bool

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::is_torsion_free]:
    Source: 'rust/core/src/curve.rs', lines 165:4-165:37
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::PublicKey}::is_torsion_free] -/
@[rust_fun
  "libsignal_core::curve::{libsignal_core::curve::PublicKey}::is_torsion_free"]
axiom libsignal_core.curve.PublicKey.is_torsion_free
  : libsignal_core.curve.PublicKey → Result Bool

/-- [libsignal_core::curve::{core::convert::TryFrom<&0 ([u8]), libsignal_core::curve::CurveError> for libsignal_core::curve::PublicKey}::try_from]:
    Source: 'rust/core/src/curve.rs', lines 196:4-196:57
    Name pattern: [libsignal_core::curve::{core::convert::TryFrom<libsignal_core::curve::PublicKey, &'0 [u8], libsignal_core::curve::CurveError>}::try_from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::curve::{core::convert::TryFrom<libsignal_core::curve::PublicKey, &'0 [u8], libsignal_core::curve::CurveError>}::try_from"]
axiom
  libsignal_core.curve.PublicKey.Insts.CoreConvertTryFromShared0SliceU8CurveError.try_from
  :
  Slice Std.U8 → Result (core.result.Result libsignal_core.curve.PublicKey
    libsignal_core.curve.CurveError)

/-- [libsignal_core::curve::{core::convert::TryFrom<&0 ([u8]), libsignal_core::curve::CurveError> for libsignal_core::curve::PrivateKey}::try_from]:
    Source: 'rust/core/src/curve.rs', lines 315:4-315:57
    Name pattern: [libsignal_core::curve::{core::convert::TryFrom<libsignal_core::curve::PrivateKey, &'0 [u8], libsignal_core::curve::CurveError>}::try_from]
    Visibility: public -/
@[rust_fun
  "libsignal_core::curve::{core::convert::TryFrom<libsignal_core::curve::PrivateKey, &'0 [u8], libsignal_core::curve::CurveError>}::try_from"]
axiom
  libsignal_core.curve.PrivateKey.Insts.CoreConvertTryFromShared0SliceU8CurveError.try_from
  :
  Slice Std.U8 → Result (core.result.Result libsignal_core.curve.PrivateKey
    libsignal_core.curve.CurveError)

/-- [subtle::{core::convert::From<subtle::Choice> for bool}::from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 153:4-153:35
    Name pattern: [subtle::{core::convert::From<bool, subtle::Choice>}::from]
    Visibility: public -/
@[rust_fun "subtle::{core::convert::From<bool, subtle::Choice>}::from"]
axiom Bool.Insts.CoreConvertFromChoice.from : subtle.Choice → Result Bool


-- The following M4-baseline axioms have been removed from this point onward:
--   * subtle::ConstantTimeEq for Slice/U8 (uses subtle.ConstantTimeEq trait, not extracted)
--   * typenum::bit::B0/B1 instance axioms (typenum.bit.B0/B1 not in current TypesPreBase)
--   * typenum::uint::UTerm and UInt instance axioms for {Clone, Default, Unsigned}
--   * signal_crypto::{aes_cbc, aes_ctr, aes_gcm, hash} primitive axioms
-- All reference types no longer reachable after the M5 PQXDH-focused extraction
-- surface (libsignal_protocol::pqxdh start_from set; no AES/GCM/CBC/hash/typenum
-- in the type graph). Restore from git history if extraction widens to include
-- the signal-crypto crate again.

-- ── PQXDH axioms ported from FunsExternal_Template.lean ─────────────────
-- These axioms model functions marked opaque in aeneas-config.yml (M5 Plan A):
-- DH primitive (calculate_agreement), ML-KEM-1024 encapsulate (libcrux oracle),
-- HKDF closures (HandshakeKeys.{derive, derive_with_label}), RNG bridges
-- (rand_core::RngCore for T), Option accessors on Initiator/RecipientParameters,
-- the KemKeyKind.key_length oracle, and pqxdh_accept (INTERIM M09 opaque).

/-- [core::ops::deref::{core::ops::deref::Deref<T> for &0 mut (T)}::deref]:
    Source: '/rustc/library/core/src/ops/deref.rs', lines 172:4-172:25
    Name pattern: [core::ops::deref::{core::ops::deref::Deref<&'0 mut @T, @T>}::deref]
    Visibility: public -/
@[rust_fun
  "core::ops::deref::{core::ops::deref::Deref<&'0 mut @T, @T>}::deref"]
axiom Mut0T.Insts.CoreOpsDerefDeref.deref {T : Type} : T → Result T

/-- [core::ops::deref::{core::ops::deref::DerefMut<T> for &0 mut (T)}::deref_mut]:
    Source: '/rustc/library/core/src/ops/deref.rs', lines 280:4-280:37
    Name pattern: [core::ops::deref::{core::ops::deref::DerefMut<&'0 mut @T, @T>}::deref_mut]
    Visibility: public -/
@[rust_fun
  "core::ops::deref::{core::ops::deref::DerefMut<&'0 mut @T, @T>}::deref_mut"]
axiom Mut0T.Insts.CoreOpsDerefDerefMut.deref_mut
  {T : Type} : T → Result (T × (T → T))

/-- [core::result::{core::result::Result<T, E>}::map_err]:
    Source: '/rustc/library/core/src/result.rs', lines 962:4-964:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map_err]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map_err"]
axiom core.result.Result.map_err
  {T : Type} {E : Type} {F : Type} {O : Type} (opsfunctionFnOnceOTupleEFInst :
  core.ops.function.FnOnce O E F) :
  core.result.Result T E → O → Result (core.result.Result T F)

/-- [alloc::boxed::{core::convert::AsRef<T> for alloc::boxed::Box<T>}::as_ref]:
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2281:4-2281:26
    Name pattern: [alloc::boxed::{core::convert::AsRef<Box<@T>, @T>}::as_ref]
    Visibility: public -/
@[rust_fun "alloc::boxed::{core::convert::AsRef<Box<@T>, @T>}::as_ref"]
axiom Box.Insts.CoreConvertAsRef.as_ref {T : Type} (A : Type) : T → Result T

-- (uuid.Uuid.as_bytes and uuid.builder.Uuid.from_slice are already hand-
--  implemented as `def`s earlier in this file; not re-axiomatized here.)

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::calculate_agreement]:
    Source: 'rust/core/src/curve.rs', lines 296:4-296:93
    Name pattern: [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::calculate_agreement]
    Visibility: public -/
@[rust_fun
  "libsignal_core::curve::{libsignal_core::curve::PrivateKey}::calculate_agreement"]
axiom libsignal_core.curve.PrivateKey.calculate_agreement
  :
  libsignal_core.curve.PrivateKey → libsignal_core.curve.PublicKey → Result
    (core.result.Result (Slice Std.U8) libsignal_core.curve.CurveError)

/-- [rand_core::{rand_core::RngCore for T}::fill_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 173:4-173:44
    Name pattern: [rand_core::{rand_core::RngCore<@T>}::fill_bytes]
    Visibility: public -/
@[rust_fun "rand_core::{rand_core::RngCore<@T>}::fill_bytes"]
axiom rand_core.RngCore.Blanket.fill_bytes
  {T : Type} {Clause0_Clause0_Target : Type} (coreopsderefDerefMutInst :
  core.ops.deref.DerefMut T Clause0_Clause0_Target) (RngCoreInst :
  rand_core.RngCore Clause0_Clause0_Target) :
  T → Slice Std.U8 → Result (T × (Slice Std.U8))

/-- [rand_core::{rand_core::RngCore for T}::next_u64]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 168:4-168:33
    Name pattern: [rand_core::{rand_core::RngCore<@T>}::next_u64]
    Visibility: public -/
@[rust_fun "rand_core::{rand_core::RngCore<@T>}::next_u64"]
axiom rand_core.RngCore.Blanket.next_u64
  {T : Type} {Clause0_Clause0_Target : Type} (coreopsderefDerefMutInst :
  core.ops.deref.DerefMut T Clause0_Clause0_Target) (RngCoreInst :
  rand_core.RngCore Clause0_Clause0_Target) :
  T → Result (Std.U64 × T)

/-- [rand_core::{rand_core::RngCore for T}::next_u32]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 163:4-163:33
    Name pattern: [rand_core::{rand_core::RngCore<@T>}::next_u32]
    Visibility: public -/
@[rust_fun "rand_core::{rand_core::RngCore<@T>}::next_u32"]
axiom rand_core.RngCore.Blanket.next_u32
  {T : Type} {Clause0_Clause0_Target : Type} (coreopsderefDerefMutInst :
  core.ops.deref.DerefMut T Clause0_Clause0_Target) (RngCoreInst :
  rand_core.RngCore Clause0_Clause0_Target) :
  T → Result (Std.U32 × T)

/-- [libsignal_protocol::kem::kyber1024::{libsignal_protocol::kem::Parameters for libsignal_protocol::kem::kyber1024::Parameters}::encapsulate]:
    Source: 'rust/protocol/src/kem/kyber1024.rs', lines 31:4-40:5 -/
axiom
  kem.kyber1024.Parameters.Insts.Libsignal_protocolKemParameters.encapsulate
  {R : Type} (rand_coreCryptoRngInst : rand_core.CryptoRng R) :
  kem.KeyMaterial kem.Public → R → Result ((core.result.Result ((Slice
    Std.U8) × (Slice Std.U8)) kem.BadKEMKeyLength) × R)

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::KeyKind for libsignal_protocol::kem::Public}::key_length]:
    Source: 'rust/protocol/src/kem.rs', lines 265:4-267:5
    Visibility: public -/
axiom kem.Public.Insts.Libsignal_protocolKemKeyKind.key_length
  : kem.KeyType → Result Std.Usize

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::HandshakeKeys}::derive]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 77:4-82:5 -/
axiom pqxdh.HandshakeKeys.derive : Slice Std.U8 → Result pqxdh.HandshakeKeys

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::HandshakeKeys}::derive_with_label]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 84:4-96:5 -/
axiom pqxdh.HandshakeKeys.derive_with_label
  : Slice Std.U8 → Slice Std.U8 → Result pqxdh.HandshakeKeys

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::InitiatorParameters}::their_one_time_pre_key]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 175:4-177:5
    Visibility: public -/
axiom pqxdh.InitiatorParameters.impl.their_one_time_pre_key
  :
  pqxdh.InitiatorParameters → Result (Option libsignal_core.curve.PublicKey)

/-- [libsignal_protocol::pqxdh::{libsignal_protocol::pqxdh::RecipientParameters}::our_one_time_pre_key_pair]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 297:4-299:5
    Visibility: public -/
axiom pqxdh.RecipientParameters.impl.our_one_time_pre_key_pair
  : pqxdh.RecipientParameters → Result (Option libsignal_core.curve.KeyPair)

/-- [libsignal_protocol::pqxdh::pqxdh_accept]:
    Source: 'rust/protocol/src/pqxdh.rs', lines 331:0-381:1
    NOTE: M09 INTERIM — body axiomatic pending AENEAS-010 resolution.
          Must be reverted to a transparent extraction in Phase B. -/
axiom pqxdh.pqxdh_accept
  :
  pqxdh.RecipientParameters → Result (core.result.Result pqxdh.HandshakeKeys
    error.SignalProtocolError)
