-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [signal_crypto]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
import Libsignal.Code.TypesPre
import Libsignal.Code.TypesExternalPre
open signal_crypto
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048


/-- [core::num::niche_types::NonZeroU64Inner]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 22:8-22:32
    Name pattern: [core::num::niche_types::NonZeroU64Inner]
    Visibility: public -/
@[rust_type "core::num::niche_types::NonZeroU64Inner"]
axiom core.num.niche_types.NonZeroU64Inner : Type

/-- [core::num::niche_types::NonZeroU8Inner]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 22:8-22:32
    Name pattern: [core::num::niche_types::NonZeroU8Inner]
    Visibility: public -/
@[rust_type "core::num::niche_types::NonZeroU8Inner"]
axiom core.num.niche_types.NonZeroU8Inner : Type

/-- [core::num::nonzero::NonZero]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 127:0-127:40
    Name pattern: [core::num::nonzero::NonZero]
    Visibility: public -/
@[rust_type "core::num::nonzero::NonZero"]
axiom core.num.nonzero.NonZero (T : Type) (Clause0_NonZeroInner : Type) : Type

/-- [aes::soft::Aes256]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aes-0.8.4/src/soft.rs', lines 42:8-44:9
    Name pattern: [aes::soft::Aes256]
    Visibility: public -/
@[rust_type "aes::soft::Aes256"]
axiom aes.soft.Aes256 : Type

/-- [ghash::GHash]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ghash-0.5.1/src/lib.rs', lines 58:0-58:16
    Name pattern: [ghash::GHash]
    Visibility: public -/
@[rust_type "ghash::GHash"]
axiom ghash.GHash : Type

/-- [uuid::Uuid]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/lib.rs', lines 457:0-457:15
    Name pattern: [uuid::Uuid]
    Visibility: public -/
@[rust_type "uuid::Uuid"]
structure uuid.Uuid where
  bytes : Array Std.U8 16#usize

/-- [uuid::error::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uuid-1.19.0/src/error.rs', lines 5:0-5:16
    Name pattern: [uuid::error::Error]
    Visibility: public -/
@[rust_type "uuid::error::Error"]
axiom uuid.error.Error : Type

/-- [rand::distr::distribution::Iter]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.4/src/distr/distribution.rs', lines 125:0-125:24
    Name pattern: [rand::distr::distribution::Iter]
    Visibility: public -/
@[rust_type "rand::distr::distribution::Iter"]
axiom rand.distr.distribution.Iter (D : Type) (R : Type) (T : Type) : Type

/-- [rand::distr::distribution::Map]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.4/src/distr/distribution.rs', lines 163:0-163:26
    Name pattern: [rand::distr::distribution::Map]
    Visibility: public -/
@[rust_type "rand::distr::distribution::Map"]
axiom rand.distr.distribution.Map (D : Type) (F : Type) (T : Type) (S : Type) :
  Type

/-- [subtle::Choice]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 120:0-120:17
    Name pattern: [subtle::Choice]
    Visibility: public -/
@[rust_type "subtle::Choice"]
axiom subtle.Choice : Type

/-- [typenum::uint::UInt]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 148:0-148:21
    Name pattern: [typenum::uint::UInt]
    Visibility: public -/
@[rust_type "typenum::uint::UInt"]
axiom typenum.uint.UInt (U : Type) (B : Type) : Type

/-- [signal_crypto::aes_ctr::Aes256Ctr32]
    Source: 'rust/crypto/src/aes_ctr.rs', lines 16:0-18:1
    Visibility: public -/
axiom aes_ctr.Aes256Ctr32 : Type

/-- [signal_crypto::hash::CryptographicMac]
    Source: 'rust/crypto/src/hash.rs', lines 14:0-17:1
    Visibility: public -/
axiom hash.CryptographicMac : Type

/-- [signal_crypto::hash::CryptographicHash]
    Source: 'rust/crypto/src/hash.rs', lines 54:0-58:1
    Visibility: public -/
axiom hash.CryptographicHash : Type
