-- Generated by scripts/split-types.ts from Aeneas output.
-- These definitions have been moved here from TypesExternal_Template.lean.
-- [signal_crypto]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
import Libsignal.Code.TypesPreBase
open signal_crypto
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048



