-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_protocol]: type definitions
import Aeneas
import Libsignal.Code.TypesPreBase
import Libsignal.Code.TypesExternalPre
import Libsignal.Code.TypesPre
import Libsignal.Code.TypesExternal
import Libsignal.Code.FunsPre
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace libsignal_protocol


/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 814:0-814:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [libsignal_core::address::ServiceIdKind]
    Source: 'rust/core/src/address.rs', lines 19:0-19:22
    Name pattern: [libsignal_core::address::ServiceIdKind]
    Visibility: public -/
@[discriminant u8, rust_type "libsignal_core::address::ServiceIdKind"]
inductive libsignal_core.address.ServiceIdKind where
| Aci : libsignal_core.address.ServiceIdKind
| Pni : libsignal_core.address.ServiceIdKind

/-- [libsignal_core::address::SpecificServiceId]
    Source: 'rust/core/src/address.rs', lines 63:0-63:48
    Name pattern: [libsignal_core::address::SpecificServiceId]
    Visibility: public -/
@[rust_type "libsignal_core::address::SpecificServiceId"]
structure libsignal_core.address.SpecificServiceId (RAW_KIND : Std.U8) where
  uuid : uuid.Uuid

/-- [libsignal_core::address::ServiceId]
    Source: 'rust/core/src/address.rs', lines 185:0-185:18
    Name pattern: [libsignal_core::address::ServiceId]
    Visibility: public -/
@[discriminant isize, rust_type "libsignal_core::address::ServiceId"]
inductive libsignal_core.address.ServiceId where
| Aci :
  libsignal_core.address.SpecificServiceId 0#u8 →
  libsignal_core.address.ServiceId
| Pni :
  libsignal_core.address.SpecificServiceId 1#u8 →
  libsignal_core.address.ServiceId

/-- [libsignal_core::address::DeviceId]
    Source: 'rust/core/src/address.rs', lines 684:0-684:19
    Name pattern: [libsignal_core::address::DeviceId]
    Visibility: public -/
@[rust_type "libsignal_core::address::DeviceId"]
structure libsignal_core.address.DeviceId where
  id : core.num.nonzero.NonZero Std.U8 core.num.niche_types.NonZeroU8Inner

/-- [libsignal_core::address::ProtocolAddress]
    Source: 'rust/core/src/address.rs', lines 777:0-777:26
    Name pattern: [libsignal_core::address::ProtocolAddress]
    Visibility: public -/
@[rust_type "libsignal_core::address::ProtocolAddress"]
structure libsignal_core.address.ProtocolAddress where
  «name» : String
  device_id : libsignal_core.address.DeviceId

/-- [libsignal_core::e164::E164]
    Source: 'rust/core/src/e164.rs', lines 13:0-13:15
    Name pattern: [libsignal_core::e164::E164]
    Visibility: public -/
@[rust_type "libsignal_core::e164::E164"]
structure libsignal_core.e164.E164 where
  inner : core.num.nonzero.NonZero Std.U64 core.num.niche_types.NonZeroU64Inner

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure]
    Source: 'rust/core/src/e164.rs', lines 27:55-27:62
    Name pattern: [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure] -/
@[reducible, rust_type
  "libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure"]
def libsignal_core.e164.E164.from_be_bytes.closure := Unit

/-- [libsignal_protocol::protocol::CiphertextMessageType]
    Source: 'rust/protocol/src/protocol.rs', lines 35:0-40:1
    Visibility: public -/
@[discriminant u8 [2,3,7,8]]
inductive protocol.CiphertextMessageType where
| Whisper : protocol.CiphertextMessageType
| PreKey : protocol.CiphertextMessageType
| SenderKey : protocol.CiphertextMessageType
| Plaintext : protocol.CiphertextMessageType

/-- [libsignal_protocol::kem::KeyType]
    Source: 'rust/protocol/src/kem.rs', lines 207:0-216:1
    Visibility: public -/
@[discriminant isize]
inductive kem.KeyType where
| Kyber1024 : kem.KeyType

/-- [libsignal_protocol::error::SignalProtocolError]
    Source: 'rust/protocol/src/error.rs', lines 18:0-112:1
    Visibility: public -/
@[discriminant isize]
inductive error.SignalProtocolError where
| InvalidArgument : String → error.SignalProtocolError
| InvalidState : Str → String → error.SignalProtocolError
| InvalidProtobufEncoding : error.SignalProtocolError
| CiphertextMessageTooShort : Std.Usize → error.SignalProtocolError
| LegacyCiphertextVersion : Std.U8 → error.SignalProtocolError
| UnrecognizedCiphertextVersion : Std.U8 → error.SignalProtocolError
| UnrecognizedMessageVersion : Std.U32 → error.SignalProtocolError
| NoKeyTypeIdentifier : error.SignalProtocolError
| BadKeyType : Std.U8 → error.SignalProtocolError
| BadKeyLength :
  libsignal_core.curve.KeyType →
  Std.Usize →
  error.SignalProtocolError
| InvalidKeyAgreement : error.SignalProtocolError
| SignatureValidationFailed : error.SignalProtocolError
| UntrustedIdentity :
  libsignal_core.address.ProtocolAddress →
  error.SignalProtocolError
| InvalidPreKeyId : error.SignalProtocolError
| InvalidSignedPreKeyId : error.SignalProtocolError
| InvalidKyberPreKeyId : error.SignalProtocolError
| InvalidMacKeyLength : Std.Usize → error.SignalProtocolError
| NoSenderKeyState : uuid.Uuid → error.SignalProtocolError
| InvalidProtocolAddress : String → Std.U32 → error.SignalProtocolError
| SessionNotFound :
  libsignal_core.address.ProtocolAddress →
  error.SignalProtocolError
| InvalidSessionStructure : Str → error.SignalProtocolError
| InvalidSenderKeySession : uuid.Uuid → error.SignalProtocolError
| InvalidRegistrationId :
  libsignal_core.address.ProtocolAddress →
  Std.U32 →
  error.SignalProtocolError
| DuplicatedMessage : Std.U32 → Std.U32 → error.SignalProtocolError
| InvalidMessage :
  protocol.CiphertextMessageType →
  Str →
  error.SignalProtocolError
| FfiBindingError : String → error.SignalProtocolError
| InvalidSealedSenderMessage : String → error.SignalProtocolError
| UnknownSealedSenderVersion : Std.U8 → error.SignalProtocolError
| SealedSenderSelfSend : error.SignalProtocolError
| UnknownSealedSenderServerCertificateId :
  Std.U32 →
  error.SignalProtocolError
| BadKEMKeyType : Std.U8 → error.SignalProtocolError
| WrongKEMKeyType : Std.U8 → Std.U8 → error.SignalProtocolError
| BadKEMKeyLength : kem.KeyType → Std.Usize → error.SignalProtocolError
| BadKEMCiphertextLength :
  kem.KeyType →
  Std.Usize →
  error.SignalProtocolError

/-- [libsignal_protocol::identity_key::IdentityKey]
    Source: 'rust/protocol/src/identity_key.rs', lines 24:0-26:1
    Visibility: public -/
structure identity_key.IdentityKey where
  public_key : libsignal_core.curve.PublicKey

/-- [libsignal_protocol::identity_key::IdentityKeyPair]
    Source: 'rust/protocol/src/identity_key.rs', lines 111:0-114:1
    Visibility: public -/
structure identity_key.IdentityKeyPair where
  identity_key : identity_key.IdentityKey
  private_key : libsignal_core.curve.PrivateKey

/-- [libsignal_protocol::kem::KeyMaterial]
    Source: 'rust/protocol/src/kem.rs', lines 280:0-284:1 -/
structure kem.KeyMaterial (T : Type) where
  data : Slice Std.U8
  kind : core.marker.PhantomData T

/-- [libsignal_protocol::kem::Public]
    Source: 'rust/protocol/src/kem.rs', lines 262:0-262:18
    Visibility: public -/
inductive kem.Public where

/-- [libsignal_protocol::kem::BadKEMKeyLength]
    Source: 'rust/protocol/src/kem.rs', lines 197:0-197:23 -/
@[reducible]
def kem.BadKEMKeyLength := Unit

/-- [libsignal_protocol::kem::Secret]
    Source: 'rust/protocol/src/kem.rs', lines 270:0-270:18
    Visibility: public -/
inductive kem.Secret where

/-- [libsignal_protocol::kem::DecapsulateError]
    Source: 'rust/protocol/src/kem.rs', lines 200:0-203:1 -/
@[discriminant isize]
inductive kem.DecapsulateError where
| BadKeyLength : kem.DecapsulateError
| BadCiphertext : kem.DecapsulateError

/-- Trait declaration: [libsignal_protocol::kem::KeyKind]
    Source: 'rust/protocol/src/kem.rs', lines 258:0-260:1
    Visibility: public -/
structure kem.KeyKind (Self : Type) where
  key_length : kem.KeyType → Result Std.Usize

/-- [libsignal_protocol::kem::Key]
    Source: 'rust/protocol/src/kem.rs', lines 308:0-311:1
    Visibility: public -/
structure kem.Key (T : Type) where
  key_type : kem.KeyType
  key_data : kem.KeyMaterial T

/-- [libsignal_protocol::kem::Ciphertext]
    Source: 'rust/protocol/src/kem.rs', lines 509:0-512:1 -/
structure kem.Ciphertext where
  key_type : kem.KeyType
  data : Slice Std.U8

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Public>}::encapsulate::closure]
    Source: 'rust/protocol/src/kem.rs', lines 368:21-370:13 -/
@[reducible]
def kem.KeyPublic.encapsulate.closure (R : Type) := kem.Key kem.Public

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Secret>}::decapsulate::closure]
    Source: 'rust/protocol/src/kem.rs', lines 403:21-410:13 -/
def kem.KeySecret.decapsulate.closure := kem.Key kem.Secret × Slice Std.U8

/-- [libsignal_protocol::kem::KeyPair]
    Source: 'rust/protocol/src/kem.rs', lines 460:0-463:1
    Visibility: public -/
structure kem.KeyPair where
  public_key : kem.Key kem.Public
  secret_key : kem.Key kem.Secret

/-- [libsignal_protocol::pqxdh::Pqxdh]
    Source: 'rust/protocol/src/pqxdh.rs', lines 36:0-36:24 -/
@[reducible]
def pqxdh.Pqxdh := Unit

/-- [libsignal_protocol::ratchet::keys::RootKey]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 186:0-188:1 -/
structure ratchet.keys.RootKey where
  key : Array Std.U8 32#usize

/-- [libsignal_protocol::ratchet::keys::ChainKey]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 142:0-145:1 -/
structure ratchet.keys.ChainKey where
  key : Array Std.U8 32#usize
  index : Std.U32

/-- [libsignal_protocol::pqxdh::HandshakeKeys]
    Source: 'rust/protocol/src/pqxdh.rs', lines 69:0-73:1 -/
structure pqxdh.HandshakeKeys where
  root_key : ratchet.keys.RootKey
  chain_key : ratchet.keys.ChainKey
  pqr_key : Array Std.U8 32#usize

/-- [libsignal_protocol::pqxdh::InitiatorAgreement]
    Source: 'rust/protocol/src/pqxdh.rs', lines 105:0-108:1 -/
structure pqxdh.InitiatorAgreement where
  keys : pqxdh.HandshakeKeys
  kyber_ciphertext : Slice Std.U8

/-- [libsignal_protocol::pqxdh::InitiatorParameters]
    Source: 'rust/protocol/src/pqxdh.rs', lines 115:0-126:1
    Visibility: public -/
structure pqxdh.InitiatorParameters where
  our_identity_key_pair : identity_key.IdentityKeyPair
  our_ephemeral_key_pair : libsignal_core.curve.KeyPair
  their_identity_key : identity_key.IdentityKey
  their_signed_pre_key : libsignal_core.curve.PublicKey
  their_one_time_pre_key : Option libsignal_core.curve.PublicKey
  their_ratchet_key : libsignal_core.curve.PublicKey
  their_kyber_pre_key : kem.Key kem.Public
  self_session : Bool

/-- [libsignal_protocol::pqxdh::RecipientParameters]
    Source: 'rust/protocol/src/pqxdh.rs', lines 250:0-261:1
    Visibility: public -/
structure pqxdh.RecipientParameters where
  our_identity_key_pair : identity_key.IdentityKeyPair
  our_signed_pre_key_pair : libsignal_core.curve.KeyPair
  our_one_time_pre_key_pair : Option libsignal_core.curve.KeyPair
  our_kyber_pre_key_pair : kem.KeyPair
  their_identity_key : identity_key.IdentityKey
  their_ephemeral_key : libsignal_core.curve.PublicKey
  their_kyber_ciphertext : Slice Std.U8
  self_session : Bool


end libsignal_protocol

