-- Generated by scripts/split-types.ts from Aeneas output.
-- These definitions have been moved here from Types.lean.
-- Defs with no axiom dependencies. See types_pre_base in aeneas-config.yml.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace signal_crypto


/-- Trait declaration: [core::num::nonzero::private::Sealed]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 46:12-46:28
    Name pattern: [core::num::nonzero::private::Sealed]
    Visibility: public -/
@[rust_trait "core::num::nonzero::private::Sealed"]
structure core.num.nonzero.private.Sealed (Self : Type) where

/-- Trait declaration: [core::num::nonzero::ZeroablePrimitive]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 33:0-33:66
    Name pattern: [core::num::nonzero::ZeroablePrimitive]
    Visibility: public -/
@[rust_trait "core::num::nonzero::ZeroablePrimitive"
  (parentClauses := ["markerCopyInst", "privateSealedInst", "markerCopyInst"])]
structure core.num.nonzero.ZeroablePrimitive (Self : Type) (Self_NonZeroInner :
  Type) where
  markerCopyInst : core.marker.Copy Self
  privateSealedInst : core.num.nonzero.private.Sealed Self
  markerCopyInst1 : core.marker.Copy Self_NonZeroInner

/-- [typenum::uint::UTerm]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 50:0-50:16
    Name pattern: [typenum::uint::UTerm]
    Visibility: public -/
@[reducible, rust_type "typenum::uint::UTerm"]
def typenum.uint.UTerm := Unit

/-- [typenum::bit::B1]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 33:0-33:13
    Name pattern: [typenum::bit::B1]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B1"]
def typenum.bit.B1 := Unit

/-- [typenum::bit::B0]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 20:0-20:13
    Name pattern: [typenum::bit::B0]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B0"]
def typenum.bit.B0 := Unit

/-- Trait declaration: [typenum::sealed::Sealed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 154:4-154:20
    Name pattern: [typenum::sealed::Sealed]
    Visibility: public -/
@[rust_trait "typenum::sealed::Sealed"]
structure typenum.sealed.Sealed (Self : Type) where

/-- Trait declaration: [typenum::marker_traits::Unsigned]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 59:0-59:53
    Name pattern: [typenum::marker_traits::Unsigned]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Unsigned"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "U16", "U32", "U64", "USIZE", "I8", "I16", "I32", "I64", "ISIZE"])]
structure typenum.marker_traits.Unsigned (Self : Type) where
  U8 : Result Std.U8
  U16 : Result Std.U16
  U32 : Result Std.U32
  U64 : Result Std.U64
  USIZE : Result Std.Usize
  I8 : Result Std.I8
  I16 : Result Std.I16
  I32 : Result Std.I32
  I64 : Result Std.I64
  ISIZE : Result Std.Isize
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  to_u8 : Result Std.U8
  to_u16 : Result Std.U16
  to_u32 : Result Std.U32
  to_u64 : Result Std.U64
  to_usize : Result Std.Usize
  to_i8 : Result Std.I8
  to_i16 : Result Std.I16
  to_i32 : Result Std.I32
  to_i64 : Result Std.I64
  to_isize : Result Std.Isize

/-- Trait declaration: [typenum::marker_traits::Bit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 35:0-35:48
    Name pattern: [typenum::marker_traits::Bit]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Bit"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "BOOL"])]
structure typenum.marker_traits.Bit (Self : Type) where
  U8 : Result Std.U8
  BOOL : Result Bool
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  new : Result Self
  to_u8 : Result Std.U8
  to_bool : Result Bool

/-- Trait declaration: [rand_core::RngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 130:0-130:17
    Name pattern: [rand_core::RngCore]
    Visibility: public -/
@[rust_trait "rand_core::RngCore"]
structure rand_core.RngCore (Self : Type) where
  next_u32 : Self → Result (Std.U32 × Self)
  next_u64 : Self → Result (Std.U64 × Self)
  fill_bytes : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))

/-- Trait declaration: [rand_core::CryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 204:0-204:28
    Name pattern: [rand_core::CryptoRng]
    Visibility: public -/
@[rust_trait "rand_core::CryptoRng" (parentClauses := ["RngCoreInst"])]
structure rand_core.CryptoRng (Self : Type) where
  RngCoreInst : rand_core.RngCore Self

/-- Trait declaration: [rand::rng::Rng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.4/src/rng.rs', lines 58:0-58:22
    Name pattern: [rand::rng::Rng]
    Visibility: public -/
@[rust_trait "rand::rng::Rng" (parentClauses := ["rand_coreRngCoreInst"])]
structure rand.rng.Rng (Self : Type) where
  rand_coreRngCoreInst : rand_core.RngCore Self

/-- Trait declaration: [rand::distr::distribution::Distribution]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.4/src/distr/distribution.rs', lines 35:0-35:25
    Name pattern: [rand::distr::distribution::Distribution]
    Visibility: public -/
@[rust_trait "rand::distr::distribution::Distribution"]
structure rand.distr.distribution.Distribution (Self : Type) (T : Type) where
  sample : forall {R : Type} (rngRngInst : rand.rng.Rng R), Self → R →
    Result (T × R)

/-- [rand::distr::StandardUniform]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.4/src/distr/mod.rs', lines 214:0-214:26
    Name pattern: [rand::distr::StandardUniform]
    Visibility: public -/
@[reducible, rust_type "rand::distr::StandardUniform"]
def rand.distr.StandardUniform := Unit

/-- Trait declaration: [rand::rng::Fill]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.4/src/rng.rs', lines 366:0-366:14
    Name pattern: [rand::rng::Fill]
    Visibility: public -/
@[rust_trait "rand::rng::Fill"]
structure rand.rng.Fill (Self : Type) where
  fill : forall {R : Type} (RngInst : rand.rng.Rng R), Self → R → Result
    (Self × R)

/-- [derive_more::convert::try_from::TryFromReprError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/derive_more-2.1.1/src/convert.rs', lines 17:4-17:34
    Name pattern: [derive_more::convert::try_from::TryFromReprError]
    Visibility: public -/
@[rust_type "derive_more::convert::try_from::TryFromReprError"]
structure derive_more.convert.try_from.TryFromReprError (T : Type) where
  input : T

/-- [signal_crypto::aes_cbc::EncryptionError]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 13:0-16:1
    Visibility: public -/
@[discriminant isize]
inductive aes_cbc.EncryptionError where
| BadKeyOrIv : aes_cbc.EncryptionError

/-- [signal_crypto::aes_cbc::DecryptionError]
    Source: 'rust/crypto/src/aes_cbc.rs', lines 19:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive aes_cbc.DecryptionError where
| BadKeyOrIv : aes_cbc.DecryptionError
| BadCiphertext : Str → aes_cbc.DecryptionError

/-- [signal_crypto::error::Error]
    Source: 'rust/crypto/src/error.rs', lines 7:0-18:1
    Visibility: public -/
@[discriminant isize]
inductive error.Error where
| UnknownAlgorithm : Str → String → error.Error
| InvalidKeySize : error.Error
| InvalidNonceSize : error.Error
| InvalidInputSize : error.Error
| InvalidTag : error.Error

/-- [libsignal_core::address::InvalidDeviceId]
    Source: 'rust/core/src/address.rs', lines 691:0-691:26
    Name pattern: [libsignal_core::address::InvalidDeviceId]
    Visibility: public -/
@[reducible, rust_type "libsignal_core::address::InvalidDeviceId"]
def libsignal_core.address.InvalidDeviceId := Unit

/-- [libsignal_core::curve::KeyType]
    Source: 'rust/core/src/curve.rs', lines 15:0-15:16
    Name pattern: [libsignal_core::curve::KeyType]
    Visibility: public -/
@[discriminant isize, rust_type "libsignal_core::curve::KeyType"]
inductive libsignal_core.curve.KeyType where
| Djb : libsignal_core.curve.KeyType

/-- [libsignal_core::curve::CurveError]
    Source: 'rust/core/src/curve.rs', lines 34:0-34:19
    Name pattern: [libsignal_core::curve::CurveError]
    Visibility: public -/
@[discriminant isize, rust_type "libsignal_core::curve::CurveError"]
inductive libsignal_core.curve.CurveError where
| NoKeyTypeIdentifier : libsignal_core.curve.CurveError
| BadKeyType : Std.U8 → libsignal_core.curve.CurveError
| BadKeyLength :
  libsignal_core.curve.KeyType →
  Std.Usize →
  libsignal_core.curve.CurveError
| InvalidKeyAgreement : libsignal_core.curve.CurveError

/-- [libsignal_core::curve::PublicKeyData]
    Source: 'rust/core/src/curve.rs', lines 59:0-59:18
    Name pattern: [libsignal_core::curve::PublicKeyData] -/
@[discriminant isize, rust_type "libsignal_core::curve::PublicKeyData"]
inductive libsignal_core.curve.PublicKeyData where
| DjbPublicKey : Array Std.U8 32#usize → libsignal_core.curve.PublicKeyData

/-- [libsignal_core::curve::PublicKey]
    Source: 'rust/core/src/curve.rs', lines 64:0-64:20
    Name pattern: [libsignal_core::curve::PublicKey]
    Visibility: public -/
@[rust_type "libsignal_core::curve::PublicKey"]
structure libsignal_core.curve.PublicKey where
  key : libsignal_core.curve.PublicKeyData

/-- [libsignal_core::curve::PrivateKeyData]
    Source: 'rust/core/src/curve.rs', lines 232:0-232:19
    Name pattern: [libsignal_core::curve::PrivateKeyData] -/
@[discriminant isize, rust_type "libsignal_core::curve::PrivateKeyData"]
inductive libsignal_core.curve.PrivateKeyData where
| DjbPrivateKey : Array Std.U8 32#usize → libsignal_core.curve.PrivateKeyData

/-- [libsignal_core::curve::PrivateKey]
    Source: 'rust/core/src/curve.rs', lines 237:0-237:21
    Name pattern: [libsignal_core::curve::PrivateKey]
    Visibility: public -/
@[rust_type "libsignal_core::curve::PrivateKey"]
structure libsignal_core.curve.PrivateKey where
  key : libsignal_core.curve.PrivateKeyData

/-- [libsignal_core::curve::KeyPair]
    Source: 'rust/core/src/curve.rs', lines 321:0-321:18
    Name pattern: [libsignal_core::curve::KeyPair]
    Visibility: public -/
@[rust_type "libsignal_core::curve::KeyPair"]
structure libsignal_core.curve.KeyPair where
  public_key : libsignal_core.curve.PublicKey
  private_key : libsignal_core.curve.PrivateKey


end signal_crypto

